name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Debug

    - name: Build UI Test Binary
      run: |
        dotnet build SuperStarTrek/SuperStarTrek.csproj -c TestDebug -p:DefineConstants="DISABLE_KEY_WAIT" -o SuperStarTrek.Test/bin/Debug/
        chmod +x SuperStarTrek.Test/bin/Debug/SuperStarTrek

    - name: Run Tests
      run: |
        mkdir results
        dotnet test --no-build --configuration Debug --verbosity normal --logger "html;logfilename=testResults.html" --results-directory results --collect:"XPlat Code Coverage"

    - name: Generate coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator \
          -reports:"results/**/coverage.cobertura.xml" \
          -targetdir:"coverage-report" \
          -reporttypes:"HtmlInline_AzurePipelines;TextSummary"

    - name: Email Test Results
      uses: dawidd6/action-send-mail@v5
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "Team Project Test Results - branch=${{ github.ref_name }}"
        to: ${{ vars.NOTIFICATION_LIST }}
        from: CPSC 5210 Team Project
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://results/testResults.html

    - name: Email Coverage Results
      uses: dawidd6/action-send-mail@v5
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "Team Project Coverage Results - branch=${{ github.ref_name }}"
        to: ${{ vars.NOTIFICATION_LIST }}
        from: CPSC 5210 Team Project
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://coverage-report/index.html
